[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".powerline-fonts"]
    type = "git-repo"
    url = "https://github.com/powerline/fonts"
    refreshPeriod = "168h"
